### ISSUE TITLE
--konnector-image option does not deploy correctly

### ISSUE THREAD

**Issue by nicks** [kube-bind/kube-bind#144]
If I use:

```
kubectl bind apiservice --konnector-image=... ...
```

kube-bind deploys the custom image, then immediately deploys over it with the official image. The output looks like this:

```
🚀 Deploying konnector v0.3.0 to namespace kube-bind with custom image "path/to/custom/konnector".
🚀 Deploying konnector v0.3.0 to namespace kube-bind.
```

is that intentional?

I worked around this by using `kubectl bind apiservice --skip-konnector --konnector-image=...`, which, counterintuitively, correctly deploys the konnector.

**Comment by pkbhowmick** [comment]
Hi @nicks ,
I believe this is a bug! If you don't mind, I have a fix for it!

**Comment by nicks** [comment]
ooh nice!!! thanks @pkbhowmick
