### ISSUE TITLE
Bug: No storage version on CRDs with webhook conversion

### ISSUE THREAD

**Issue by lhaendler** [kube-bind/kube-bind#168]
# Problem description
If a CRD uses webhook conversion logic, only one version is propagated to a consumer cluster. This will be the first version in the CRD. However, the first version is not necessarily the storage version. If it is not, the CRD creation on the consumer cluster will fail, as the CRD has no storage version. The line responsible is linked below.

https://github.com/kube-bind/kube-bind/blob/83421bd5d106f55f35ef1d1e60f5526f059defa1/pkg/apis/kubebind/v1alpha1/helpers/serviceexport.go#L117

# How to fix
There are two approaches for fixing this issue:
1. Changing the selection logic to use the storage version of the CRD.  
    This approach would give the provider more control over which apiVersion gets installed into the consumer cluster.
3. Making the selected version of the CRD the storage version on the consumer cluster.  
    This would keep the semantics closer to the existing behavior.

**Comment by sttts** [comment]
Would rather expect the backend to select a version. The storage version has no relevance for the bound version, it might only be a hint.
